# _config.yml
title: "Reflexiones Académicas"
description: "Blog académico de Andrea Bascur"
author: "Andrea Bascur"
email: "ambascurpinto@gmail.com"
baseurl: ""
url: "https://ambascur.github.io"

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Configuración de posts
permalink: /:categories/:year/:month/:day/:title/

# Configuración de build
exclude:
  - Gemfile
  - Gemfile.lock