# ==========================================
# ARCHIVO: _config.yml
# ==========================================

title: "Reflexiones Académicas"
description: "Blog académico de Andrea Bascur"
author: "Andrea Bascur"
email: "a.bascur@universidad.edu"
baseurl: ""
url: "https://tu-usuario.github.io"

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock